version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverlessrepo-alexa-skills-kit-nodejs-factskill"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5bqjnpv2tjq6"
s3_prefix = "serverlessrepo-alexa-skills-kit-nodejs-factskill"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

